version: "3.9"

services:
 backend:
  build:
   context: .
   dockerfile: backend/Dockerfile
  container_name: cogniFlow-backend
  env_file:
   - backend/.env
  ports:
   - "8080:80"
  depends_on:
   - postgres
   - chromadb
  restart: always
  volumes:
   - ./backend/app:/app

 frontend:
  build:
   context: .
   dockerfile: frontend/Dockerfile
  container_name: cogniFlow-frontend
  env_file:
   - frontend/.env
  ports:
   - "3000:5173"
  restart: always
  volumes:
   - ./frontend:/app
   - /app/node_modules

 postgres:
  image: postgres:15
  container_name: cogniFlow-postgres
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: cogniflow
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  restart: always

 chromadb:
  image: chromadb/chroma:latest
  container_name: cogniFlow-chromadb
  ports:
   - "8000:8001"
  restart: always

 pgadmin:
  image: dpage/pgadmin4
  container_name: cogniFlow-pgadmin
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@admin.com
   PGADMIN_DEFAULT_PASSWORD: admin
  ports:
   - "5050:80"
  depends_on:
   - postgres
  restart: always

volumes:
 postgres_data:
