"""one chroma_doc_id for each postgres doc

Revision ID: 060a4d2554c2
Revises: 69458b9cf4d0
Create Date: 2025-09-09 14:24:42.119920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '060a4d2554c2'
down_revision: Union[str, None] = '69458b9cf4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chroma_document_id', sa.String(), nullable=True))
    op.drop_column('documents', 'chroma_document_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chroma_document_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('documents', 'chroma_document_id')
    # ### end Alembic commands ###
