"""Auto migration 20250908_164527

Revision ID: 0f800f67f546
Revises: 66a27928d782
Create Date: 2025-09-08 16:45:28.101504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f800f67f546'
down_revision: Union[str, None] = '66a27928d782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('test_field', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'documents', ['test_field'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'test_field')
    # ### end Alembic commands ###
