"""new detailed schema of documents

Revision ID: 3afa41b5360f
Revises: 6338cb3cddc6
Create Date: 2025-09-09 15:42:08.523631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3afa41b5360f'
down_revision: Union[str, None] = '6338cb3cddc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add columns as nullable first
    op.add_column('documents', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('total_chunks', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chroma_chunk_ids', postgresql.ARRAY(sa.String()), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE documents SET pages = 1 WHERE pages IS NULL")
    op.execute("UPDATE documents SET total_chunks = 0 WHERE total_chunks IS NULL")
    
    # Alter columns to NOT NULL
    op.alter_column('documents', 'pages', nullable=False)
    op.alter_column('documents', 'total_chunks', nullable=False)
    
    # Create indexes
    op.create_index('ix_document_project_hash', 'documents', ['project_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index('ix_document_project_hash', table_name='documents')
    op.drop_column('documents', 'chroma_chunk_ids')
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'pages')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
