"""storing creds

Revision ID: 4b4920eb9d90
Revises: 7683867d0e43
Create Date: 2025-09-11 22:39:25.503650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4920eb9d90'
down_revision: Union[str, None] = '7683867d0e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflows_project_id', table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('definition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='workflows_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workflows_pkey')
    )
    op.create_index('ix_workflows_project_id', 'workflows', ['project_id'], unique=True)
    # ### end Alembic commands ###
