"""Auto migration 20250908_164151

Revision ID: 4bd4ee8b8f7d
Revises: 941673007880
Create Date: 2025-09-08 16:41:51.986632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd4ee8b8f7d'
down_revision: Union[str, None] = '941673007880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
