"""add document fields for chromadb integration

Revision ID: 6338cb3cddc6
Revises: 060a4d2554c2
Create Date: 2025-09-09 15:26:54.899363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6338cb3cddc6"
down_revision: Union[str, None] = "060a4d2554c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add nullable columns first
    op.add_column("documents", sa.Column("content_hash", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("pages", sa.Integer(), nullable=True))
    op.add_column("documents", sa.Column("total_chunks", sa.Integer(), nullable=True))
    op.add_column(
        "documents",
        sa.Column("chroma_document_ids", postgresql.ARRAY(sa.String()), nullable=True),
    )

    # Update existing rows with default values
    op.execute("UPDATE documents SET pages = 0 WHERE pages IS NULL")
    op.execute("UPDATE documents SET total_chunks = 0 WHERE total_chunks IS NULL")

    # Now alter columns to be NOT NULL
    op.alter_column("documents", "pages", nullable=False)
    op.alter_column("documents", "total_chunks", nullable=False)

    # Create indexes
    op.create_index(
        "ix_document_project_hash",
        "documents",
        ["project_id", "content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes first
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_index("ix_document_project_hash", table_name="documents")

    # Drop columns
    op.drop_column("documents", "chroma_document_ids")
    op.drop_column("documents", "total_chunks")
    op.drop_column("documents", "pages")
    op.drop_column("documents", "content_hash")
    # ### end Alembic commands ###
