"""Auto migration 20250908_164235

Revision ID: 66a27928d782
Revises: 4bd4ee8b8f7d
Create Date: 2025-09-08 16:42:36.298733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a27928d782'
down_revision: Union[str, None] = '4bd4ee8b8f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
