"""storing creds

Revision ID: 7683867d0e43
Revises: 2fdb34606f1d
Create Date: 2025-09-11 22:38:11.099424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7683867d0e43'
down_revision: Union[str, None] = '2fdb34606f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=False),
    sa.Column('embedding_model_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_nodes_project_id'), 'knowledge_base_nodes', ['project_id'], unique=True)
    op.create_table('llm_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('openai_api_key', sa.String(), nullable=False),
    sa.Column('llm_model_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_nodes_project_id'), 'llm_nodes', ['project_id'], unique=True)
    op.create_table('web_search_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('serpapi_api_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_search_nodes_project_id'), 'web_search_nodes', ['project_id'], unique=True)
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_project_id'), 'workflows', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_project_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_web_search_nodes_project_id'), table_name='web_search_nodes')
    op.drop_table('web_search_nodes')
    op.drop_index(op.f('ix_llm_nodes_project_id'), table_name='llm_nodes')
    op.drop_table('llm_nodes')
    op.drop_index(op.f('ix_knowledge_base_nodes_project_id'), table_name='knowledge_base_nodes')
    op.drop_table('knowledge_base_nodes')
    # ### end Alembic commands ###
