"""storing creds

Revision ID: 9b5a00f1a9c8
Revises: 291b9190f38b
Create Date: 2025-09-11 23:30:27.869573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5a00f1a9c8'
down_revision: Union[str, None] = '291b9190f38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_project_id'), 'workflows', ['project_id'], unique=True)
    op.drop_index('ix_workflow_nodes_project_id', table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_nodes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('definition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='workflow_nodes_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workflow_nodes_pkey')
    )
    op.create_index('ix_workflow_nodes_project_id', 'workflow_nodes', ['project_id'], unique=True)
    op.drop_index(op.f('ix_workflows_project_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
