"""file upload to pockity

Revision ID: afb91c6f3f8c
Revises: 3afa41b5360f
Create Date: 2025-09-11 03:18:57.207084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb91c6f3f8c'
down_revision: Union[str, None] = '3afa41b5360f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_url')
    # ### end Alembic commands ###
