"""chroma document ids

Revision ID: c0ec08dde30a
Revises: 5a2ec7baa8d5
Create Date: 2025-09-09 13:20:42.636912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0ec08dde30a'
down_revision: Union[str, None] = '5a2ec7baa8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chroma_document_ids', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_index('ix_documents_embedding_metadata_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'embedding_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_embedding_metadata_gin', 'documents', ['embedding_metadata'], unique=False, postgresql_using='gin')
    op.drop_column('documents', 'chroma_document_ids')
    # ### end Alembic commands ###
