"""Auto migration 20250908_164839

Revision ID: fee210b18ef9
Revises: 0f800f67f546
Create Date: 2025-09-08 16:48:39.805406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee210b18ef9'
down_revision: Union[str, None] = '0f800f67f546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_test_field_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_test_field_fkey', 'messages', 'documents', ['test_field'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
